language: python
python:
  - "3.9"
env:
  - SECRET_KEY=asdfghjkjbgd
  - DATABASE_URI= "postgresql://postgres:postgres@localhost:5432/demodb"
services:
  - postgresql

before_script:
 - psql -c 'create database demodb;' -U postgres

 - export DATABASE_URI="postgresql://postgres:postgres@localhost:5432/demodb"
 - export TESTDB_URI="postgresql://postgres:postgres@localhost:5432/demodb"
 - export FLASK_ENV=testing

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov

after_success:
  - coveralls
  - codecov
